server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: report-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: localhost:${spring.application.name}:${server.port}